# Generated by Django 6.0.5 on 2026-05-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
